### ISSUE TITLE
bot downloads file perfectly but throws error while uploading

### ISSUE THREAD

**Issue by CarlA007** [Spark-X-Cloud/SparkXcloud-Gdrive-MirrorBot#1]
bot.helper.mirror_utils.upload_utils.gdriveTools - ERROR - <HttpError 404 when requesting None returned "File not found: 1ylNFs4GytLpywcq0pPfCN9-ImtAEMZLJ.". Details: "[{'domain': 'global', 'reason': 'notFound', 'message': 'File not found: 1ylNFs4GytLpywcq0pPfCN9-ImtAEMZLJ.', 'locationType': 'parameter', 'location': 'fileId'}]">

**Comment by harshhaareddy** [comment]
> bot.helper.mirror_utils.upload_utils.gdriveTools - ERROR - <HttpError 404 when requesting None returned "File not found: 1ylNFs4GytLpywcq0pPfCN9-ImtAEMZLJ.". Details: "[{'domain': 'global', 'reason': 'notFound', 'message': 'File not found: 1ylNFs4GytLpywcq0pPfCN9-ImtAEMZLJ.', 'locationType': 'parameter', 'location': 'fileId'}]">

ur token.pickle file is not properly done. Create again token.pickle, if error from gdrive tools, its probably from ur side fix ur side
