### ISSUE TITLE
feature requested

### ISSUE THREAD

**Issue by narutouzumaki271** [Spark-X-Cloud/SparkXcloud-Gdrive-MirrorBot#23]
the spark x cloud mirror bot appearance is too good
and work fine 
but some feature is missing like
bot pm 
mirror log
leech log
auto delete upload message 

as of missing these feature in bot the telegram mirror group got ban due to copyright issue. if these feature is present then there should be nothing in mirror group all there leech mirror file directly send to bot
please add these feature

**Comment by kawinpattanai** [comment]
Yes

**Comment by harshhaareddy** [comment]
sure we will try to add new features ...

**Comment by harshhaareddy** [comment]
_Sure we will try to add new features .._

Thanks for using **`Spark-X-Cloud`** 😊😊😊
