### ISSUE TITLE
why do I face this error while deploying through heroku?

### ISSUE THREAD

**Issue by Callistor** [Spark-X-Cloud/SparkXcloud-Gdrive-MirrorBot#24]
Run akhileshns/heroku-deploy@v3.12.12
Created and wrote to ~/.netrc
 ›   Warning: Our terms of service have changed: 
Successfully logged into heroku
 ›   https://dashboard.heroku.com/terms-of-service
WARNING! Your password will be stored unencrypted in /home/runner/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
 ›   Error: Couldn't find that app.
 ›
 ›   Error ID: not_found
Creating ***... done, region is us, stack is container
Setting CONFIG_FILE_URL and restarting ***... done, v3
pull access denied for anasty17/mltb, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
 ▸    Error: docker build exited with Error: 1
            Unable to push branch because the branch is behind the deployed branch. Using --force to deploy branch. 
            (If you want to avoid this, set dontuseforce to 1 in with: of .github/workflows/action.yml. 
            Specifically, the error was: Error: Command failed: heroku container:push web --app *** 
pull access denied for anasty17/mltb, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
 ▸    Error: docker build exited with Error: 1
pull access denied for anasty17/mltb, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Error: Error: Command failed: heroku container:push web --app *** 
pull access denied for anasty17/mltb, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
 ▸    Error: docker build exited with Error: 1
 ▸    Error: docker build exited with Error: 1

**Comment by sssira** [comment]
same like me, it's created the app on heroku but there's no dyno to start

**Comment by Callistor** [comment]
> same like me, it's created the app on heroku but there's no dyno to start

yeah tried a few times still dont work

**Comment by harshhaareddy** [comment]
**Issue Fixed 👍  re-deploy it..**
