### ISSUE TITLE
Facing issue when using 'upstream' branch as upstream branch in config.env 

### ISSUE THREAD

**Issue by fabcodes30** [Spark-X-Cloud/SparkXcloud-Gdrive-MirrorBot#28]
![image](https://user-images.githubusercontent.com/54717628/182373803-3621dcb3-665b-425c-a891-c97ff53d3c94.png)

Says no module named mega

**Comment by harshhaareddy** [comment]
**Deploy upstream branch .. kindly follow deploying instructions/guide**
